apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - backend.yaml
  - frontend.yaml
  # - ingress.yaml   # uncomment for managed clouds with ingress-nginx

images:
  - name: ghcr.io/manaf/ckad-backend
    newTag: local
  - name: ghcr.io/manaf/ckad-frontend
    newTag: local
